---
cluster.name: ${CLUSTER_NAME}

node.name: ${NODE_NAME}
node.master: ${NODE_MASTER}
node.data: ${NODE_DATA}

path.data: ${PATH_DATA}
path.logs: ${PATH_DATA}/logs

bootstrap.memory_lock: true
security.manager.enabled: false

network.host: 0.0.0.0

index.auto_expand_replicas: ${INDEX_AUTO_EXPAND_REPLICAS}
index.number_of_shards: ${INDEX_NUMBER_OF_SHARDS}
index.number_of_replicas: ${INDEX_NUMBER_OF_REPLICAS}
index.refresh_interval: ${INDEX_REFRESH_INTERVAL}

http.enabled: ${HTTP_ENABLE}
http.compression: true
http.bind_host: ${HTTP_BIND_HOST}

cloud.kubernetes.service: ${KUBERNETES_SERVICE}
cloud.kubernetes.namespace: ${KUBERNETES_NAMESPACE}
discovery.type: kubernetes
discovery.zen.ping.multicast.enabled: false
discovery.zen.fd.ping_interval: ${DISCOVERY_ZEN_FD_PING_INTERVAL}
discovery.zen.fd.ping_timeout: ${DISCOVERY_ZEN_FD_PING_TIMEOUT}
discovery.zen.fd.ping_retries: ${DISCOVERY_ZEN_FD_PING_RETRIES}
discovery.zen.publish_timeout: ${DISCOVERY_ZEN_PUBLISH_TIMEOUT}

searchguard.ssl.transport.enabled: ${ENABLE_TRANSPORT_SSL}
searchguard.ssl.transport.keystore_filepath: certs/keystore.jks
searchguard.ssl.transport.keystore_alias: cert
searchguard.ssl.transport.resolve_hostname: false

searchguard.ssl.transport.truststore_filepath: certs/truststore.jks
searchguard.ssl.transport.truststore_alias: ca

# searchguard.ssl.http.keystore_filepath: certs/keystore.jks
# searchguard.ssl.http.keystore_alias: cert
# searchguard.ssl.http.truststore_filepath: certs/truststore.jks
# searchguard.ssl.http.truststore_alias: ca
